'use client';

import Link from 'next/link';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, BarChart3, Check, Code2, FileSearch, Gauge, Globe2, Lightbulb, PenTool, Sparkles } from 'lucide-react';

type Tier = { name: string; label: string; price: string; cadence?: string; positioning: string; includes: string[] };
type Service = { id: string; title: string; eyebrow: string; description: string; icon: typeof FileSearch; accent: string; tiers: Tier[] };

const services: Service[] = [
  { id: 'seo-audits', title: 'SEO Audit', eyebrow: 'Clarity before momentum', description: 'A precise view of what is holding your website back, with a prioritised path to better search visibility.', icon: FileSearch, accent: 'from-cyan-400 to-sky-500', tiers: [
    { name: 'Foundation', label: 'Entry', price: '₦75,000', positioning: 'For businesses that need to understand their biggest SEO problems.', includes: ['Technical SEO health check', 'Indexation check', 'On-page review', 'Core Web Vitals assessment', 'Basic keyword review', 'Search Console review', 'Prioritised recommendations', 'SEO audit report'] },
    { name: 'Growth', label: 'Growth', price: '₦150,000', positioning: 'For businesses that want a complete diagnosis and actionable roadmap.', includes: ['Full technical SEO audit', 'Keyword research', 'Competitor analysis', 'Content gap analysis', 'Backlink profile analysis', 'Schema and internal linking review', 'UX and conversion review', 'Implementation roadmap', 'Strategy session'] },
    { name: 'Authority', label: 'Premium', price: '₦300,000', positioning: 'For complex or highly competitive websites that need deeper intelligence.', includes: ['Advanced technical audit', 'Competitive SERP analysis', 'Keyword opportunity analysis', 'Content architecture', 'Technical architecture review', 'Link authority analysis', 'Conversion funnel analysis', 'AI-search visibility analysis', '90-day SEO roadmap'] },
  ] },
  { id: 'monthly-seo', title: 'Monthly SEO', eyebrow: 'A consistent organic growth engine', description: 'Ongoing strategy and execution for teams ready to turn search into a dependable acquisition channel.', icon: BarChart3, accent: 'from-amber-300 to-orange-500', tiers: [
    { name: 'Foundation', label: 'Entry', price: '₦150,000', cadence: '/month', positioning: 'For small businesses establishing organic visibility.', includes: ['SEO onboarding', 'Keyword research', 'Up to 5 priority pages/month', 'Technical SEO fixes', 'On-page SEO', 'Internal linking', 'Search Console and analytics monitoring', 'Basic local SEO', 'Monthly report'] },
    { name: 'Growth', label: 'Growth', price: '₦300,000', cadence: '/month', positioning: 'For businesses looking to consistently generate qualified traffic and leads.', includes: ['Everything in Foundation', 'Up to 10 priority pages/month', '2 SEO content assets/month', 'Competitor monitoring', 'Content gap analysis', 'Advanced technical SEO', 'Schema and local SEO', 'Link-building campaign', 'Conversion recommendations', 'Monthly strategy meeting'] },
    { name: 'Authority', label: 'Premium', price: '₦550,000', cadence: '/month', positioning: 'For businesses aggressively competing for valuable search positions.', includes: ['Everything in Growth', '15–20 priority pages/month', '4 SEO content assets/month', 'Aggressive content strategy', 'Digital PR and link acquisition', 'SERP intelligence', 'Entity optimisation', 'AI-search visibility optimisation', 'Bi-weekly reporting', 'Dedicated strategist and priority support'] },
  ] },
  { id: 'local-seo', title: 'Local SEO', eyebrow: 'Be found where business happens', description: 'Make your locations, services and reputation easier to discover in local search and Google Maps.', icon: Globe2, accent: 'from-emerald-300 to-teal-500', tiers: [
    { name: 'Foundation', label: 'Entry', price: '₦100,000', cadence: '/month', positioning: 'For businesses building a reliable local search presence.', includes: ['Google Business Profile optimisation', 'NAP consistency', 'Local keyword research', 'Citation cleanup', 'Review strategy', 'Local schema', 'Monthly reporting'] },
    { name: 'Growth', label: 'Growth', price: '₦200,000', cadence: '/month', positioning: 'For local brands ready to compete for more high-intent searches.', includes: ['Everything in Foundation', 'Monthly GBP optimisation', 'Location and content assets', 'Competitor monitoring', 'Citation building', 'Review acquisition system', 'Local landing-page optimisation', 'Local link-building', 'Map Pack tracking'] },
    { name: 'Authority', label: 'Premium', price: '₦350,000', cadence: '/month', positioning: 'For multi-location or category-leading businesses.', includes: ['Everything in Growth', 'Multiple location pages', 'Multi-location SEO', 'Advanced GBP management', 'Local link acquisition', 'Competitor intelligence', 'Review growth system', 'Local content strategy', 'Advanced local schema', 'Detailed local ranking reports'] },
  ] },
  { id: 'technical-seo', title: 'Technical SEO', eyebrow: 'Make the site easier to crawl, use and trust', description: 'Remove technical friction across architecture, indexation, structured data and performance foundations.', icon: Code2, accent: 'from-violet-300 to-indigo-500', tiers: [
    { name: 'Foundation', label: 'Entry', price: '₦150,000', positioning: 'For a clean, dependable technical baseline.', includes: ['Technical SEO audit', 'Crawlability and indexation', 'XML sitemap', 'Robots.txt', 'Canonicals', 'Basic structured data', 'Core Web Vitals recommendations'] },
    { name: 'Growth', label: 'Growth', price: '₦300,000', positioning: 'For teams ready to implement meaningful technical improvements.', includes: ['Everything in Foundation', 'Core Web Vitals fixes', 'JavaScript SEO', 'Schema implementation', 'Internal linking improvements', 'Image optimisation', 'Mobile performance improvements', 'Search Console monitoring', 'Implementation support'] },
    { name: 'Authority', label: 'Premium', price: 'Starting from ₦600,000', positioning: 'For large, complex or fast-changing websites.', includes: ['Full technical architecture', 'Advanced JavaScript SEO', 'Large-site crawl analysis', 'Programmatic SEO', 'Advanced structured data', 'Performance engineering', 'International SEO architecture', 'Website migration SEO', 'Technical implementation', 'Developer collaboration'] },
  ] },
  { id: 'content-seo', title: 'Content SEO', eyebrow: 'Build topical authority with intent', description: 'Turn search demand into a clear editorial system that attracts the right audience and supports conversion.', icon: PenTool, accent: 'from-rose-300 to-pink-500', tiers: [
    { name: 'Foundation', label: 'Entry', price: '₦150,000', cadence: '/month', positioning: 'For teams creating a stronger content foundation.', includes: ['Keyword research', 'Topic mapping', '2 optimised content assets', 'On-page optimisation', 'Internal linking', 'Monthly reporting'] },
    { name: 'Growth', label: 'Growth', price: '₦300,000', cadence: '/month', positioning: 'For businesses building a repeatable content growth programme.', includes: ['Everything in Foundation', '4 content assets', 'Topic cluster strategy', 'Pillar page strategy', 'Competitor content analysis', 'Conversion-focused copy', 'Content refreshes', 'Internal linking strategy'] },
    { name: 'Authority', label: 'Premium', price: '₦550,000', cadence: '/month', positioning: 'For brands competing to own a valuable topic space.', includes: ['Everything in Growth', '6–8 content assets', 'Advanced pillar and cluster architecture', 'Competitive SERP analysis', 'Digital PR opportunities', 'Content refresh programme', 'Commercial landing pages', 'Comparison pages', 'Entity authority strategy', 'AI-search optimised content'] },
  ] },
  { id: 'performance-optimization', title: 'Performance SEO', eyebrow: 'Faster experiences, stronger foundations', description: 'Improve measurable site performance and Core Web Vitals without making promises no responsible agency can keep.', icon: Gauge, accent: 'from-fuchsia-300 to-rose-500', tiers: [
    { name: 'Foundation', label: 'Entry', price: '₦100,000', positioning: 'For teams that need a clear performance baseline.', includes: ['Website performance audit', 'Core Web Vitals analysis', 'LCP, INP and CLS analysis', 'Image optimisation recommendations', 'Performance roadmap'] },
    { name: 'Growth', label: 'Growth', price: '₦250,000', positioning: 'For businesses ready to implement meaningful speed improvements.', includes: ['Everything in Foundation', 'Core Web Vitals implementation', 'JavaScript optimisation', 'Image and font optimisation', 'Caching improvements', 'CDN recommendations', 'Lazy loading', 'Third-party script optimisation', 'Mobile performance optimisation'] },
    { name: 'Authority', label: 'Premium', price: '₦500,000+', positioning: 'For products where performance is a serious competitive advantage.', includes: ['Everything in Growth', 'Advanced performance engineering', 'Code splitting', 'Rendering optimisation', 'Advanced JavaScript performance', 'Infrastructure and CDN optimisation', 'Continuous performance monitoring', 'Regression monitoring', 'Developer collaboration', 'Technical performance strategy'] },
  ] },
  { id: 'consulting', title: 'SEO Consulting', eyebrow: 'Senior thinking for your next move', description: 'Bring experienced SEO direction into the room when your team needs clarity, challenge and practical next steps.', icon: Lightbulb, accent: 'from-sky-300 to-cyan-500', tiers: [
    { name: 'Foundation', label: 'Entry', price: '₦75,000', positioning: 'A one-time strategic session for an important SEO decision.', includes: ['90-minute SEO strategy session', 'Website review', 'Key SEO problems', 'Growth opportunities', 'Strategic recommendations', 'Follow-up action summary'] },
    { name: 'Growth', label: 'Growth', price: '₦200,000', cadence: '/month', positioning: 'For teams that want a trusted advisor in their operating rhythm.', includes: ['2 strategy sessions/month', 'SEO roadmap', 'Technical SEO reviews', 'Content strategy', 'Competitor analysis', 'Monthly recommendations', 'Performance review'] },
    { name: 'Authority', label: 'Premium', price: '₦400,000', cadence: '/month', positioning: 'For leadership teams needing senior SEO involvement week to week.', includes: ['Weekly strategic involvement', 'Technical reviews', 'Content direction', 'Developer guidance', 'SEO roadmap', 'Competitor intelligence', 'Executive reporting', 'Priority advisory support'] },
  ] },
];

export default function ServicesCatalogueClient() {
  const [activeId, setActiveId] = useState(services[0].id);
  const activeService = services.find((service) => service.id === activeId) ?? services[0];
  const ActiveIcon = activeService.icon;

  return (
    <main className="overflow-hidden bg-slate-950 text-slate-100">
      <section className="relative isolate border-b border-white/10 px-4 pb-16 pt-36 sm:px-6 sm:pb-24 lg:px-8">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_0%,rgba(14,165,233,0.2),transparent_34%),radial-gradient(circle_at_90%_20%,rgba(245,158,11,0.13),transparent_28%)]" />
        <div className="container mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.15fr_0.85fr] lg:items-end">
          <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.65 }}>
            <p className="mb-5 flex items-center gap-2 font-mono text-xs uppercase tracking-[0.24em] text-cyan-300"><Sparkles className="h-4 w-4" /> Organic growth, engineered</p>
            <h1 className="max-w-4xl text-5xl font-semibold tracking-[-0.04em] text-white sm:text-7xl">SEO that earns its place in your growth plan.</h1>
            <p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">Choose the problem you need to solve. We will bring the technical depth, strategic clarity and steady execution to move it forward.</p>
          </motion.div>
          <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15, duration: 0.65 }} className="border-l border-cyan-300/40 pl-6 lg:mb-2"><p className="font-mono text-xs uppercase tracking-[0.22em] text-slate-500">NerdPace / Services index</p><p className="mt-4 text-2xl leading-snug text-slate-200">Seven focused offers. One honest standard: no guaranteed rankings, just rigorous work you can measure.</p></motion.div>
        </div>
      </section>

      <section className="px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="container mx-auto max-w-7xl">
        <div className="mb-12 flex flex-col gap-5 border-b border-white/10 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-slate-500">01 / Select a discipline</p><h2 className="mt-3 text-3xl font-semibold text-white sm:text-4xl">The right lever for right now.</h2></div><p className="max-w-md text-sm leading-6 text-slate-400">Start with a focused engagement or build a longer-term organic growth system around your goals.</p></div>
        <div className="grid gap-10 lg:grid-cols-[240px_1fr] lg:gap-16">
          <nav aria-label="SEO services" className="flex gap-2 overflow-x-auto pb-2 lg:block lg:space-y-2 lg:overflow-visible lg:pb-0">{services.map((service, index) => { const Icon = service.icon; const isActive = service.id === activeService.id; return <button key={service.id} type="button" aria-current={isActive ? 'page' : undefined} onClick={() => setActiveId(service.id)} className={`group flex min-w-max items-center gap-3 border px-4 py-3 text-left text-sm transition-all lg:flex lg:w-full ${isActive ? 'border-cyan-300/60 bg-cyan-300/10 text-white' : 'border-white/10 text-slate-400 hover:border-white/25 hover:text-white'}`}><span className="font-mono text-xs text-slate-600">0{index + 1}</span><Icon className={`h-4 w-4 ${isActive ? 'text-cyan-300' : 'text-slate-500 group-hover:text-cyan-300'}`} /><span>{service.title}</span></button>; })}</nav>
          <div key={activeService.id} className="min-w-0"><motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }}><div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="mb-3 flex items-center gap-3"><span className={`grid h-11 w-11 place-items-center bg-gradient-to-br ${activeService.accent} text-slate-950`}><ActiveIcon className="h-5 w-5" /></span><p className="font-mono text-xs uppercase tracking-[0.18em] text-slate-400">{activeService.eyebrow}</p></div><h3 className="text-4xl font-semibold tracking-tight text-white">{activeService.title}</h3></div><p className="max-w-md text-sm leading-6 text-slate-400 sm:text-right">{activeService.description}</p></div>
            <div className="grid gap-5 xl:grid-cols-3">{activeService.tiers.map((tier, index) => <Link key={tier.name} href={`/services/${activeService.id}`} className={`group relative flex h-full flex-col border p-6 transition-all duration-300 hover:-translate-y-1 hover:border-cyan-300/60 hover:bg-white/[0.06] sm:p-7 ${index === 1 ? 'border-cyan-300/50 bg-cyan-300/[0.07] shadow-[0_0_45px_rgba(34,211,238,0.08)]' : 'border-white/10 bg-white/[0.025]'}`}><div className="mb-9 flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-500">{tier.label}</p><h4 className="mt-2 text-2xl font-semibold text-white">{tier.name}</h4></div>{index === 1 && <span className="whitespace-nowrap bg-cyan-300 px-2 py-1 font-mono text-[9px] font-bold tracking-[0.12em] text-slate-950">MOST POPULAR</span>}</div><p className="min-h-[72px] text-sm leading-6 text-slate-400">{tier.positioning}</p><div className="my-7 border-y border-white/10 py-5"><p className="text-3xl font-semibold tracking-tight text-white">{tier.price}</p>{tier.cadence && <p className="mt-1 font-mono text-xs uppercase tracking-[0.15em] text-cyan-300">{tier.cadence}</p>}</div><p className="mb-4 font-mono text-[10px] uppercase tracking-[0.2em] text-slate-500">Includes</p><ul className="space-y-3">{tier.includes.map((item) => <li key={item} className="flex gap-3 text-sm leading-5 text-slate-300"><Check className="mt-0.5 h-4 w-4 shrink-0 text-cyan-300" />{item}</li>)}</ul><span className="mt-8 inline-flex items-center gap-2 border-t border-white/10 pt-5 text-sm font-semibold text-white group-hover:text-cyan-300">Explore {tier.name}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div>
          </motion.div></div>
        </div>
      </div></section>

      <section className="border-t border-white/10 bg-slate-900/70 px-4 py-16 sm:px-6 lg:px-8"><div className="container mx-auto flex max-w-7xl flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-cyan-300">02 / Make the next move</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold text-white sm:text-4xl">Not sure which service fits?</h2><p className="mt-3 max-w-xl leading-7 text-slate-400">Bring us the context. We will help you find the most useful starting point, without forcing your business into a package that does not fit.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/audit" className="inline-flex items-center justify-center gap-2 bg-cyan-300 px-5 py-3 font-semibold text-slate-950 transition hover:bg-cyan-200">Get a free audit <ArrowRight className="h-4 w-4" /></Link><Link href="/contact" className="inline-flex items-center justify-center border border-white/15 px-5 py-3 font-semibold text-white transition hover:border-cyan-300/60 hover:text-cyan-300">Talk to an expert</Link></div></div></section>
    </main>
  );
}
